(function(root, factory) {
    if (typeof define === 'function' && define.amd) {
        define("templates", ['jquery'], factory);
    } else if (typeof exports === 'object') {
        module.exports = factory(require('jquery'));
    } else {
        root.templates = factory(jQuery);
    }
})(this, function($) {
    var templates = {};
    templates.connecting = function (data, opts) {
        // generated by jQfy 1.3.8
        opts = $.extend({}, opts);
        data = $.extend({}, data);
        var obj = {};
        var $root = $('<div/>');
        
        var $div1 = $('<div/>')
            .addClass("container")
            .appendTo($root);
        $div1.append(document.createTextNode("\n    "));
        
        var $div2 = $('<div/>')
            .addClass("row")
            .appendTo($div1);
        $div2.append(document.createTextNode("\n        "));
        
        var $div3 = $('<div/>')
            .addClass("col-xs-12 text-center")
            .appendTo($div2);
        $div3.append(document.createTextNode("\n            "));
        
        var $i1 = $('<i/>')
            .addClass("fa fa-circle-o-notch fa-spinner fa-5x")
            .appendTo($div3);
        //     end $i1
        $div3.append(document.createTextNode("\n        "));
        //    end $div3
        $div2.append(document.createTextNode("\n    "));
        //   end $div2
        $div1.append(document.createTextNode("\n"));
        //  end $div1
        // end $root
        var output = $root.contents();
        obj.$ = output;
        return obj;
    };
    
    templates.error = function (data, opts) {
        // generated by jQfy 1.3.8
        opts = $.extend({}, opts);
        data = $.extend({}, data);
        var obj = {};
        var $root = $('<div/>');
        
        var $div1 = $('<div/>')
            .addClass("container")
            .appendTo($root);
        $div1.append(document.createTextNode("\n    "));
        
        var $div2 = $('<div/>')
            .addClass("row")
            .appendTo($div1);
        $div2.append(document.createTextNode("\n        "));
        
        var $div3 = $('<div/>')
            .addClass("col-xs-12 text-center")
            .appendTo($div2);
        $div3.append(document.createTextNode("\n            "));
        
        var $i1 = $('<i/>')
            .addClass("fa fa-warning fa-5x text-danger")
            .appendTo($div3);
        //     end $i1
        $div3.append(document.createTextNode("\n            "));
        
        var $br1 = $('<br/>')
            .appendTo($div3);
        //     end $br1
        $div3.append(document.createTextNode("\n\n            "));
        
        var $h11 = $('<h1/>')
            .addClass("text-danger")
            .appendTo($div3);
        $h11.append(document.createTextNode("Connection Failed"));
        //     end $h11
        $div3.append(document.createTextNode("\n            "));
        
        var $strong1 = $('<strong/>')
            .appendTo($div3);
        $strong1.append(document.createTextNode("Check your server"));
        //     end $strong1
        $div3.append(document.createTextNode("\n            "));
        
        var $tryBtn = $('<button/>')
            .addClass("btn btn-default")
            .appendTo($div3);
        $tryBtn.append(document.createTextNode("try again"));
        //     end $tryBtn
        $div3.append(document.createTextNode("\n        "));
        //    end $div3
        $div2.append(document.createTextNode("\n    "));
        //   end $div2
        $div1.append(document.createTextNode("\n"));
        //  end $div1
        $root.append(document.createTextNode("\n\n"));
        
        // start script 1
        
            $tryBtn.on('click', function () {
                console.log('reconnect');
                app.eventSocket.connect(app.port);
            });
        
        //  end script 1
        
        // end $root
        var output = $root.contents();
        obj.$ = output;
        return obj;
    };
    
    templates.main = function (data, opts) {
        // generated by jQfy 1.3.8
        opts = $.extend({}, opts);
        data = $.extend({}, data);
        var obj = {};
        var $root = $('<div/>');
        
        var $div1 = $('<div/>')
            .addClass("container-fluid")
            .appendTo($root);
        $div1.append(document.createTextNode("\n    "));
        
        var $div2 = $('<div/>')
            .addClass("row")
            .appendTo($div1);
        $div2.append(document.createTextNode("\n        "));
        
        var $div3 = $('<div/>')
            .addClass("col-xs-12")
            .appendTo($div2);
        $div3.append(document.createTextNode("\n            "));
        
        var $h11 = $('<h1/>')
            .addClass("text-center")
            .appendTo($div3);
        $h11.append(document.createTextNode("JG Terminal"));
        //     end $h11
        $div3.append(document.createTextNode("\n        "));
        //    end $div3
        $div2.append(document.createTextNode("\n    "));
        //   end $div2
        $div1.append(document.createTextNode("\n    "));
        
        var $div4 = $('<div/>')
            .addClass("row")
            .appendTo($div1);
        $div4.append(document.createTextNode("\n        "));
        
        var $div5 = $('<div/>')
            .addClass("col-xs-6")
            .appendTo($div4);
        $div5.append(document.createTextNode("\n            "));
        
        var $h21 = $('<h2/>')
            .appendTo($div5);
        $h21.append(document.createTextNode("Choose map"));
        //     end $h21
        $div5.append(document.createTextNode("\n        "));
        //    end $div5
        $div4.append(document.createTextNode("\n        "));
        
        var $div6 = $('<div/>')
            .addClass("col-xs-6")
            .appendTo($div4);
        $div6.append(document.createTextNode("\n            "));
        
        var $fileInput = $('<input/>')
            .addClass("hidden")
            .attr("type", "file")
            .appendTo($div6);
        //     end $fileInput
        $div6.append(document.createTextNode("\n            "));
        
        var $fileBtn = $('<button/>')
            .addClass("btn btn-default btn-block")
            .appendTo($div6);
        
        var $i1 = $('<i/>')
            .addClass("fa fa-file fa-3x")
            .appendTo($fileBtn);
        //      end $i1
        //     end $fileBtn
        $div6.append(document.createTextNode("\n            "));
        
        var $fileOutput = $('<span/>')
            .addClass("text-muted")
            .appendTo($div6);
        //     end $fileOutput
        $div6.append(document.createTextNode("\n        "));
        //    end $div6
        $div4.append(document.createTextNode("\n    "));
        //   end $div4
        $div1.append(document.createTextNode("\n    "));
        
        var $div7 = $('<div/>')
            .addClass("row")
            .appendTo($div1);
        $div7.append(document.createTextNode("\n        "));
        
        var $div8 = $('<div/>')
            .addClass("col-xs-6")
            .appendTo($div7);
        $div8.append(document.createTextNode("\n            "));
        
        var $h22 = $('<h2/>')
            .appendTo($div8);
        $h22.append(document.createTextNode("New game"));
        //     end $h22
        $div8.append(document.createTextNode("\n        "));
        //    end $div8
        $div7.append(document.createTextNode("\n        "));
        
        var $div9 = $('<div/>')
            .addClass("col-xs-6")
            .appendTo($div7);
        $div9.append(document.createTextNode("\n            "));
        
        var $newGame = $('<button/>')
            .addClass("btn btn-default btn-block")
            .appendTo($div9);
        
        var $i2 = $('<i/>')
            .addClass("fa fa-plus-square fa-3x")
            .appendTo($newGame);
        //      end $i2
        $newGame.append(document.createTextNode("\n            "));
        //     end $newGame
        $div9.append(document.createTextNode("\n        "));
        //    end $div9
        $div7.append(document.createTextNode("\n    "));
        //   end $div7
        $div1.append(document.createTextNode("\n    "));
        
        var $div10 = $('<div/>')
            .addClass("row")
            .appendTo($div1);
        $div10.append(document.createTextNode("\n        "));
        
        var $div11 = $('<div/>')
            .addClass("col-xs-6")
            .appendTo($div10);
        $div11.append(document.createTextNode("\n            "));
        
        var $h23 = $('<h2/>')
            .appendTo($div11);
        $h23.append(document.createTextNode("Run client"));
        //     end $h23
        $div11.append(document.createTextNode("\n        "));
        //    end $div11
        $div10.append(document.createTextNode("\n        "));
        
        var $div12 = $('<div/>')
            .addClass("col-xs-6")
            .appendTo($div10);
        $div12.append(document.createTextNode("\n            "));
        
        var $pre1 = $('<pre/>')
            .appendTo($div12);
        $pre1.append(document.createTextNode("$ python main.py\n$ java main.class\n$ ./main.out\n$ node index.js"));
        //     end $pre1
        $div12.append(document.createTextNode("\n        "));
        //    end $div12
        $div10.append(document.createTextNode("\n    "));
        //   end $div10
        $div1.append(document.createTextNode("\n    "));
        
        var $div13 = $('<div/>')
            .addClass("row")
            .appendTo($div1);
        $div13.append(document.createTextNode("\n        "));
        
        var $div14 = $('<div/>')
            .addClass("col-xs-6")
            .appendTo($div13);
        $div14.append(document.createTextNode("\n            "));
        
        var $h24 = $('<h2/>')
            .appendTo($div14);
        $h24.append(document.createTextNode("Start game"));
        //     end $h24
        $div14.append(document.createTextNode("\n        "));
        //    end $div14
        $div13.append(document.createTextNode("\n        "));
        
        var $div15 = $('<div/>')
            .addClass("col-xs-6")
            .appendTo($div13);
        $div15.append(document.createTextNode("\n            "));
        
        var $startBtn = $('<button/>')
            .addClass("btn btn-default btn-block")
            .appendTo($div15);
        
        var $i3 = $('<i/>')
            .addClass("fa fa-play fa-3x")
            .appendTo($startBtn);
        //      end $i3
        //     end $startBtn
        $div15.append(document.createTextNode("\n        "));
        //    end $div15
        $div13.append(document.createTextNode("\n    "));
        //   end $div13
        $div1.append(document.createTextNode("\n    "));
        
        var $div16 = $('<div/>')
            .addClass("row")
            .appendTo($div1);
        $div16.append(document.createTextNode("\n        "));
        
        var $div17 = $('<div/>')
            .addClass("col-xs-6")
            .appendTo($div16);
        $div17.append(document.createTextNode("\n            "));
        
        var $h25 = $('<h2/>')
            .appendTo($div17);
        $h25.append(document.createTextNode("Controls"));
        //     end $h25
        $div17.append(document.createTextNode("\n        "));
        //    end $div17
        $div16.append(document.createTextNode("\n        "));
        
        var $btnGroupContainer = $('<div/>')
            .addClass("col-xs-6 text-center")
            .appendTo($div16);
        $btnGroupContainer.append(document.createTextNode("\n            "));
        
        var $div19 = $('<div/>')
            .addClass("btn-group")
            .appendTo($btnGroupContainer);
        $div19.append(document.createTextNode("\n                "));
        
        var $resumeBtn = $('<button/>')
            .addClass("btn btn-default")
            .appendTo($div19);
        
        var $i4 = $('<i/>')
            .addClass("fa fa-play fa-2x")
            .appendTo($resumeBtn);
        //       end $i4
        //      end $resumeBtn
        $div19.append(document.createTextNode("\n                "));
        
        var $pauseBtn = $('<button/>')
            .addClass("btn btn-default")
            .appendTo($div19);
        
        var $i5 = $('<i/>')
            .addClass("fa fa-pause fa-2x")
            .appendTo($pauseBtn);
        //       end $i5
        //      end $pauseBtn
        $div19.append(document.createTextNode("\n                "));
        
        var $stopBtn = $('<button/>')
            .addClass("btn btn-default")
            .appendTo($div19);
        
        var $i6 = $('<i/>')
            .addClass("fa fa-stop fa-2x")
            .appendTo($stopBtn);
        //       end $i6
        //      end $stopBtn
        $div19.append(document.createTextNode("\n            "));
        //     end $div19
        $btnGroupContainer.append(document.createTextNode("\n        "));
        //    end $btnGroupContainer
        $div16.append(document.createTextNode("\n    "));
        //   end $div16
        $div1.append(document.createTextNode("\n    "));
        
        var $div20 = $('<div/>')
            .addClass("row")
            .appendTo($div1);
        $div20.append(document.createTextNode("\n        "));
        
        var $div21 = $('<div/>')
            .addClass("col-xs-12")
            .appendTo($div20);
        $div21.append(document.createTextNode("\n            "));
        
        var $output = $('<pre/>')
            .attr("id", "output")
            .appendTo($div21);
        //     end $output
        $div21.append(document.createTextNode("\n            "));
        
        var $form = $('<form/>')
            .appendTo($div21);
        $form.append(document.createTextNode("\n                "));
        
        var $input = $('<input/>')
            .addClass("form-control")
            .attr("type", "text")
            .appendTo($form);
        //      end $input
        $form.append(document.createTextNode("\n            "));
        //     end $form
        $div21.append(document.createTextNode("\n        "));
        //    end $div21
        $div20.append(document.createTextNode("\n    "));
        //   end $div20
        $div1.append(document.createTextNode("\n"));
        //  end $div1
        $root.append(document.createTextNode("\n"));
        
        // start script 1
        
        
            function appendTerminal(line) {
                var $span = $('<span>').text(line);
                $output
                        .append($span)
                        .append('\n')
                        .prop({
                            scrollTop: $output[0].scrollHeight
                        });
                return $span;
            }
        
            function command(name, args) {
                app.eventSocket.emit('command', name, args || []);
                var argStr = _(args)
                        .map(_.ary(JSON.stringify, 1))
                        .join(' ');
                appendTerminal('$ ' + name + ' ' + argStr).addClass('text-success bolder');
            }
        
            app.eventSocket.on('init', function (lines) {
                appendTerminal('init').addClass('text-danger bolder');
                _.each(lines, function (line) {
                    appendTerminal(line).addClass('text-danger');
                })
            });
        
            app.eventSocket.on('report', function (lines) {
                appendTerminal('report').addClass('text-danger bolder');
                _.each(lines, function (line) {
                    appendTerminal(line).addClass('text-danger');
                })
            });
        
            app.eventSocket.on('connect', function (lines) {
                appendTerminal('-- connect --').addClass('text-muted');
            });
            app.eventSocket.on('disconnect', function (lines) {
                appendTerminal('-- disconnect --').addClass('text-muted');
            });
            app.eventSocket.on('error', function (lines) {
                appendTerminal('-- error --').addClass('text-muted');
            });
        
            $form.on('submit', function (e) {
                e.preventDefault();
                var val = $input.val();
                val = _.trim(val);
                if (val) {
                    var args = val.split(/\s+/);
                    var name = args.shift();
                    command(name, args);
                    $input.val('');
                }
                return false;
            });
        
            $fileInput.on('change', function () {
                var val = $fileInput.val();
                if (val) {
                    var path = require('path');
                    var name = path.basename(val);
                    $fileOutput.text(name + ' selected.');
                } else {
                    $fileOutput.text('');
                }
            });
        
            $fileBtn.on('click', function () {
                $fileInput.click();
            });
        
            $newGame.on('click', function () {
                var val = $fileInput.val();
                if (val) {
                    command('newGame', [val]);
                }
            });
        
            $startBtn.on('click', function () {
                command('startGame');
            });
        
            $resumeBtn.on('click', function () {
                command('resumeGame');
            });
            $pauseBtn.on('click', function () {
                command('pauseGame');
            });
        
            $stopBtn.on('click', function () {
                command('endGame');
            });
        
            $resumeBtn.tooltip({container: $btnGroupContainer, title: 'Resume game'});
            $pauseBtn.tooltip({container: $btnGroupContainer, title: 'Pause game'});
            $stopBtn.tooltip({container: $btnGroupContainer, title: 'End game'});
        
        
        //  end script 1
        
        // end $root
        var output = $root.contents();
        obj.$ = output;
        return obj;
    };
    
    return templates;
});
